name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      #- run: docker build -t rallycoding/react-test -f ./client/Dockerfile.dev ./client
      #- run: docker run -e CI=true rallycoding/react-test npm test

      - run: docker build -t tjid421/multi-client ./client
      - run: docker build -t tjid421/multi-nginx ./nginx
      - run: docker build -t tjid421/multi-server ./server
      - run: docker build -t tjid421/multi-worker ./worker

      - run: docker push tjid421/multi-client
      - run: docker push tjid421/multi-nginx
      - run: docker push tjid421/multi-server
      - run: docker push tjid421/multi-worker

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env 
          existing_bucket_name: elasticbeanstalk-us-east-2-806083367321
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
