name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      #- run: docker build -t rallycoding/react-test -f ./client/Dockerfile.dev ./client
      #- run: docker run -e CI=true rallycoding/react-test npm test

      - run: docker build -t tjid421/multi-client ./client
      - run: docker build -t tjid421/multi-nginx ./nginx
      - run: docker build -t tjid421/multi-server ./server
      - run: docker build -t tjid421/multi-worker ./worker

      - run: docker push tjid421/multi-client
      - run: docker push tjid421/multi-nginx
      - run: docker push tjid421/multi-server
      - run: docker push tjid421/multi-worker
